### ISSUE TITLE
[Bug]: Null reference exception

### ISSUE THREAD

**Issue by YourFavoritePerson** [ShootMe/FallGuysStats#318]
### What happened?

I've been trying to keep my solo's history accurate and sometimes that involves moving random discovery games to another profile.  There is an "octa-pit" record where if i hover over it, it throws this exception:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at FallGuysStats.LevelDetails.gridDetails_CellMouseEnter(Object sender, DataGridViewCellEventArgs e) in D:\workspaces\rider\FallGuysStats\Views\LevelDetails.cs:line 907
   at System.Windows.Forms.DataGridView.OnCellMouseEnter(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This is on the latest version. DB is attached.

[data.zip](https://github.com/ShootMe/FallGuysStats/files/13802086/data.zip)

Also random question but how do you open this db?  I tried db browser for sqlite and litedbexplorer but neither could open it.

### Platform

None

**Comment by qutrits** [comment]
[data.zip](https://github.com/ShootMe/FallGuysStats/files/13802158/data.zip)

Try again with this.

**Comment by YourFavoritePerson** [comment]
that let me delete it.  :)
